### ISSUE TITLE
Doesn't Support OPTIONS or 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by williscool** [steve-jansen/json-proxy#21] opened 2015-03-08 23:42 UTC
So I can't seem to use it for anything because I'm running my json-proxy on a separate domain from the site I want to request from

**Comment by steve-jansen** [comment] 2015-03-10 02:54
Hi @williscool 

I originally wrote json-proxy as a developer tool to avoid CORS when coding HTML5 apps.  It sounds like you want to use CORS.  Can you expand a bit more on your use case? 

Cheers,
Steve

**Comment by killua99** [comment] 2015-03-18 13:45
I'm in the same situation as williscool, I'm getting that error I can guess because we use https request. I did try to change the host and referer but look like it doesn't make any effect.

I'm on dev url, and forward to real API url, but get those error.

**Comment by steve-jansen** [comment] 2015-03-18 23:28
@killua99 @williscool 

Can you post a sample config so I can reproduce your problem?

**Comment by steve-jansen** [comment] 2015-05-22 20:31
Closing - no repsonse.

**Closed by steve-jansen** 2015-05-22 20:31 UTC
Labels: question

**Comment by williscool** [comment] 2015-05-22 21:36
Sorry I never responded. Ended up using ngnix to get what I wanted to do done.

Here is an example of an ngnix conf that achieves what I wanted though

https://gist.github.com/williscool/46c377faf26011aa505a

**Comment by steve-jansen** [comment] 2015-05-23 10:21
@williscool 

Appreciate it.  Your use case looks like the corollary of the use case for json-proxy.  I created json-proxy specifically to avoid the need to configure CORS.  With json-proxy, your browser makes all requests to a single FQDN (ex. `localhost`), and json-proxy selectively proxies your request to other downstream servers based on URL patterns.  This use case is similar to how many of the apps I work on look in production - a single FQDN that load balances and aggregates different backend servers that may do different things (ex, static assets, api services).

Glad to hear nginx did the job for you - it's a workhorse.  Your nginx conf is well documente, making it super helpful.  Thanks for sharing that.

Cheers,
Steve

**Comment by williscool** [comment] 2015-05-24 17:28
Ah I see. Different use case.

But yeah figuring that nginx conf out took a few good days of googling. 

Glad you liked it
